os: linux
language: c
compiler:
  - gcc
  - clang

env:
  global:
    - DEV_PACKAGES="libc6-dev uuid-dev libpam0g-dev libcurl4-openssl-dev autotools-dev libssl-dev libsubunit-dev"
    - BUILD_PACKAGES="dh-autoreconf clang cmake pkg-config texinfo libsubunit0 checkinstall"
    - PACKAGES="$DEV_PACKAGES $BUILD_PACKAGES"

before_install:
  - sudo -H apt-get -q -qq -y update > /dev/null
  - sudo -H apt-get -q -qq -y install $PACKAGES > /dev/null

install:
  - sudo -H ci/dependencies.sh > /dev/null

stages:
  - test # travis magic because of compiler matrix
  - package
  - deploy

jobs:
  include:
  - name: create .DEB package
    stage: package
    script: sudo -H debian/deb-builder.sh
  - name: deploy to github
    stage: deploy
    if: tag IS present
    before_deploy: sudo -H debian/deb-builder.sh $TRAVIS_BRANCH
    deploy:
      - provider: releases
        api_key: $GITHUB_ROBOT_TOKEN
        overwrite: true
        cleanup: false
        edge: true
        file: trusona-server-sdk_$TRAVIS_BRANCH-1_amd64.deb
        on:
          tags: true

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "GE81cCQusHHozG9/jXDKQFKC79NcgxeALLD4UEozoLsM5ZZGAMId0axbgpJ3rb2pHZr6k2nVlmvsPrNSs3JG+z2eDYIoTFL/AfL71RniCgEK3xwT9M8ggHCHGX/fjSev9XEZjuYxc8Rcydbuw+axSdR9aVaW9H/iXkSRMVt7wz0lpIsLrvWzgBCxoFtOLElLX+u3szKiyHCkOI5E8vkZkZRwAWgZNfKpZwH4NcJ3n/DftdnsocIOqa2JAK5IeiFrm4DsWIYatmDofrzQGNAw2EV7Sxl3UZ16dlxKQZyxvWE9VDJcnp7/f1fPluNNqY22CUM3q95B040eRXokRi5nJKoRL+SHFF/V4e9YBFC3aBMJxXmWFiXepDcrSA7acxlWxLWzJ15ajckm00CiWtAYsxh48q3UBwVZJ+cgbIlL5AUX3ptkpbofXk0uPiAKCU7hFwr+/I9JI3mBAGUCfTUKG/lIHhtp7LpBIOnuRwXxrBwmjschq6ONKfiBPFD5p1NiIxJYfLM2HPdlAeisJ0ewXPlSUcCzkagH76YNwLn+B0MRwdGvPod1c5HrF5NLK++xezgWVhO0gashVDMdS5Wmo0w7lP8C8sXrC1X6uQtDUjpub1Q5I2IlOJyi5e+UjGkGJ/NzTjZGJeG+jpJUhwobj6YMD3xtkTSFl1yeIAnf/Qc="