os: linux
language: c
compiler:
  - gcc
  - clang

sudo: required

install:
  - sudo -H apt-get -q -qq -y update
  - sudo -H apt-get -q -qq -y install libc6-dev uuid-dev libpam0g-dev libcurl4-openssl-dev dh-autoreconf autotools-dev clang cmake pkg-config texinfo libssl-dev libsubunit-dev libsubunit0
  - sudo -H ./ci/dependencies.sh

script:
  - make
  - make test

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "GE81cCQusHHozG9/jXDKQFKC79NcgxeALLD4UEozoLsM5ZZGAMId0axbgpJ3rb2pHZr6k2nVlmvsPrNSs3JG+z2eDYIoTFL/AfL71RniCgEK3xwT9M8ggHCHGX/fjSev9XEZjuYxc8Rcydbuw+axSdR9aVaW9H/iXkSRMVt7wz0lpIsLrvWzgBCxoFtOLElLX+u3szKiyHCkOI5E8vkZkZRwAWgZNfKpZwH4NcJ3n/DftdnsocIOqa2JAK5IeiFrm4DsWIYatmDofrzQGNAw2EV7Sxl3UZ16dlxKQZyxvWE9VDJcnp7/f1fPluNNqY22CUM3q95B040eRXokRi5nJKoRL+SHFF/V4e9YBFC3aBMJxXmWFiXepDcrSA7acxlWxLWzJ15ajckm00CiWtAYsxh48q3UBwVZJ+cgbIlL5AUX3ptkpbofXk0uPiAKCU7hFwr+/I9JI3mBAGUCfTUKG/lIHhtp7LpBIOnuRwXxrBwmjschq6ONKfiBPFD5p1NiIxJYfLM2HPdlAeisJ0ewXPlSUcCzkagH76YNwLn+B0MRwdGvPod1c5HrF5NLK++xezgWVhO0gashVDMdS5Wmo0w7lP8C8sXrC1X6uQtDUjpub1Q5I2IlOJyi5e+UjGkGJ/NzTjZGJeG+jpJUhwobj6YMD3xtkTSFl1yeIAnf/Qc="
